### ISSUE TITLE
Criar documento de visão

### ISSUE THREAD

**Issue by GabrielBFelix** [GabrielBFelix/E-Book#11]
Criar documento de visão com:

- Introdução
- Descrição geral
- Perfis dos usuários
- Tabela de riscos
- Suposições dependências

**Comment by DarlanGabriel** [comment]
Completado em: 8285b9af231bf1ce3105758f57560874fee038cc 40f7876ffc1f8a2a58800693b0921a065e167c09 6ef6d355645875a61c4c7508a875aebdf04aa1a3 203fce7590b6a6657b97ba73949f0675baf49fa8
