### ISSUE TITLE
Criar documento com os resultados do teste de sistema

### ISSUE THREAD

**Issue by ridnave** [GabrielBFelix/E-Book#46]
Executar cada teste de aceitação dos User Stories, anotando o resultado no documento dos resultados do teste de aceitação. O relatório de Testes deve seguir esse [Modelo aqui!](https://docs.google.com/document/d/11hLKf0FcspQrDRfo3gRMXzuY1028cUeniv_Aob8DX_0/edit) 
Cadastrar issues de bugs caso os testes de aceitação não passem.

**Comment by GabrielBFelix** [comment]
Commit criando modelo do documento do relatório de testes: 9eaf3cedcd14fc7e76ce5a4de4d337f600813cd7
