### ISSUE TITLE
Remover import não usado de useState no arquivo client/src/pages/verPerfil/VerPerfil.js

### ISSUE THREAD

**Issue by ridnave** [GabrielBFelix/E-Book#54]
linha de código com code Smell -> import React, {useState} from 'react';

**Comment by DarlanGabriel** [comment]
Corrigido  nesse commit: 19a8b134491fbf9a8ab85c5a5bef2adadd18e3d2

**Comment by GabrielBFelix** [comment]
Code Smell corrigido
